name: hrows
version: 0.2.0.0
synopsis: A program to handle data in form of rows.
license: GPL-2
author:              "Juan Miguel Vilar"
maintainer:          "jvilar@uji.es"
copyright:           "2018 Juan Miguel Vilar"

dependencies:
- base >= 4.7 && < 5

data-files:
- src/hrows.css
- src/hrows.glade

library:
  source-dirs: lib
  ghc-options:
    - -Wall
  dependencies:
  - aeson
  - aeson-pretty
  - auto
  - base
  - bytestring
  - bv
  - containers
  - data-default
  - directory
  - filepath
  - gi-gdk
  - gi-gtk
  - haskell-gi-base
  - megaparsec
  - mtl
  - text
  - text-show
  - transformers
  - vector

executables:
  hrows:
    main: src/Main.hs
    ghc-options:
    - -threaded
    - -Wall
    dependencies:
    - hrows
    - auto
    - data-default
    - directory
    - gi-gtk
    - gi-gtk-hs
    - jmvOptions >= 0.2
    - lens

  testParser:
    main: src/testParser.hs
    dependencies:
    - haskeline
    - hrows
    - text

tests:
  expression-test:
    main: test/Expression.hs
    dependencies:
    - hrows
    - hspec
    - text

  lexer-test:
    main: test/Lexer.hs
    dependencies:
    - hrows
    - hspec
    - text

  sourceinfo-test:
    main: test/SourceInfo.hs
    dependencies:
    - aeson
    - bytestring
    - hrows
    - hspec

  fromRows-test:
    main: test/FromRows.hs
    dependencies:
    - hrows
    - hspec
    - text
