resolver: lts-18.13

packages:
- .

extra-deps:
- git: https://github.com/jvilar/jmvOptions.git
  commit: 5ddff6621f5f76304340c8431a01b0535c42e313
- git: https://github.com/jvilar/auto.git
  commit: c44b4a5fe12c7818a98eb1fe6f65de202050a0d0

